from django.db import models

# Create your models here.
class ActiveIngredient (models.Model):
	drug_code = models.IntegerField(default=0)
	active_ingredient_code = models.IntegerField(default=0)
	ingredient = models.CharField(max_length=240)
	ingredient_supplied_ind = models.CharField(max_length=1)
	strength = models.CharField(max_length=20)
	strength_unit = models.CharField(max_length=40)
	strength_type = models.CharField(max_length=40)
	dosage_value = models.CharField(max_length=20)
	base = models.CharField(max_length=1)
	dosage_unit = models.CharField(max_length=20)
	notes = models.CharField(max_length=2000)

class SearchQuery (models.Model):
	druga = models.CharField(max_length=100)
	drugb = models.CharField(max_length=100)

class Reports (models.Model):
	report_id = models.IntegerField(default=0)
	report_no = models.CharField(max_length=100)
	version_no = models.IntegerField(default=0)
	datreceived = models.DateField()
	datintreceived = models.DateField()
	mah_no = models.CharField(max_length=20)
	report_type_code = models.CharField(max_length=100)
	report_type_eng = models.CharField(max_length=60)
	report_type_fr = models.CharField(max_length=60)
	gender_code = models.CharField(max_length=100)
	gender_eng = models.CharField(max_length=60)
	gender_fr = models.CharField(max_length=60)
	#age = models.IntegerField(default=0)
	age = models.CharField(max_length=100)
	#age_y = models.IntegerField()
	age_unit_eng = models.CharField(max_length=60)
	age_unit_fr = models.CharField(max_length=60)
	age_bracket_eng = models.CharField(max_length=60)
	age_bracket_fr = models.CharField(max_length=60)
	outcome_code = models.CharField(max_length=100)
	outcome_code_eng = models.CharField(max_length=60)
	outcome_code_fr = models.CharField(max_length=60)
	#weight = models.IntegerField(default=0)
	weight = models.CharField(max_length=100)
	weight_unit_eng = models.CharField(max_length=60)
	weight_unit_fr = models.CharField(max_length=60)
	#height = models.IntegerField(default=0)
	height = models.CharField(max_length=100)
	height_unit_eng = models.CharField(max_length=60)
	height_unit_fr = models.CharField(max_length=60)
	seriousness_code = models.CharField(max_length=100)
	seriousness_eng = models.CharField(max_length=60)
	seriousness_fr = models.CharField(max_length=60)
	death = models.CharField(max_length=100)
	disability = models.CharField(max_length=100)
	congenital_anomaly = models.CharField(max_length=100)
	life_threatening = models.CharField(max_length=100)
	hosp_required = models.CharField(max_length=100)
	other_medically_imp_cond = models.CharField(max_length=100)
	reporter_type_eng = models.CharField(max_length=60)
	reporter_type_fr = models.CharField(max_length=60)
	source_code = models.CharField(max_length=100)
	source_code_eng = models.CharField(max_length=60)
	source_code_fr = models.CharField(max_length=60)

class ReportDrug (models.Model):
	report_drug_id = models.CharField(max_length=15)
	report_id = models.CharField(max_length=15)
	drug_product_id = models.CharField(max_length=8)
	drugname = models.CharField(max_length=255)
	druginvolv_eng = models.CharField(max_length=60)
	druginvolv_fr = models.CharField(max_length=60)
	routeadmin_eng = models.CharField(max_length=60)
	routeadmin_fr = models.CharField(max_length=60)
	unit_dose_qty = models.CharField(max_length=100)
	dose_unit_end = models.CharField(max_length=60)
	dose_unit_fr = models.CharField(max_length=60)
	frequency = models.CharField(max_length=100)
	freq_time = models.CharField(max_length=100)
	frequency_time_eng = models.CharField(max_length=30)
	frequency_time_fr = models.CharField(max_length=30)
	freq_time_unit_eng = models.CharField(max_length=60)
	freq_time_unit_fr = models.CharField(max_length=60)
	therapy_duration = models.CharField(max_length=100)
	therapy_duration_unit_eng = models.CharField(max_length=60)
	therapy_duration_unit_fr = models.CharField(max_length=60)
	dosageform_eng = models.CharField(max_length=60)
	dosageform_fr = models.CharField(max_length=60)

class Reactions (models.Model):
	reaction_id = models.IntegerField(default=0)
	report_id = models.IntegerField(default=0)
	duration = models.CharField(max_length=100)
	duration_unit_eng = models.CharField(max_length=60)
	duration_unit_fr = models.CharField(max_length=60)
	pt_name_code = models.CharField(max_length=100)
	pt_name_eng = models.CharField(max_length=250)
	pt_name_fr = models.CharField(max_length=250)
	soc_name_code = models.CharField(max_length=100)
	soc_name_eng = models.CharField(max_length=250)
	soc_name_fr = models.CharField(max_length=250)
	meddra_version = models.CharField(max_length=9)






